weights: /content/yolov5/runs/train/yolov5s6_results5/weights/last.pt
cfg: ''
data: /content/yolov5/data.yaml
hyp: data/hyps/hyp.scratch-low.yaml
epochs: 50
batch_size: 64
imgsz: 640
rect: false
resume: true
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: runs/train
name: yolov5s6_results
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs/train/yolov5s6_results5
